---
- name: "update apt"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Remove packages that are no longer used"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["tar", "unzip", "curl", "git"]
    state: latest
    update_cache: yes

- name: "install nodejs"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install npm"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install n node manager"
  become: true
  npm: 
    name: n  
    global: yes
    production: yes 

- name: "install node13.8"
  become: true
  shell: |
    n 13.8.0
    
- name: "install pm2"
  become: true
  shell: |
    npm i -g pm2  