version: 2.1
jobs:
  Build-Frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Build front-end"
          command: |
            cd frontend/
            npm install
            npm run build
  Build-Backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Build Bront-end"
          command: |
            cd backend/
            npm install
            npm run build  

workflows:
  default:
    jobs:
      - Build-Frontend
      - Build-Backend




#       - run:
#           name: Build front-end
#           command: |
#             # Your code here
#             exit 1
#       # - save_cache:
#       #     paths: [frontend/node_modules]
#       #     key: frontend-build